sustainers/website

agenda.md

to reflect a bit more Gunner's methodology.

make agenda tweaks

---

about.md

Lest people arrive with the wrong idea :)

Fix contradiction between homepage and about page.

---

index.html

it's hacky as hell but works :)

update support url

---

about.md

- Bulletize ideal attendee profile
- Expand info on Gunner (closing #30)

Rework About > Who

---

README.md

Adding Contribute and License note

---

about.md

Link the Changelog community

---

_sass/_style.scss

Standardize buttons

---

_sass/_style.scss

Fix button css on mobile

---

about.md
faq.md

Added an FAQ

---

agenda.md

Removed repeated 'no' and added oxford comma.

Grammar changes in agenda.md

---

index.html
travel-support.md

Add travel support form to the site.
Amended dates. Cut off 26th May, confirmed on 2nd June.

Add travel support

---

index.html
travel-support.md

* remove notice on index.html
* keep travel support page (cool urls don’t change) but update text

Remove travel grant form

---

Gemfile
Gemfile.lock
_config.yml
_includes/footer.html
_includes/head/social.html
_includes/header.html
_includes/nav.html
assets/img/favicons/manifest.json
index.html

There's one thing we need to consider: the title will change to `page title | page description`.

Switch to jekyll-seo-tag.

---

_sass/_main.scss
_sass/components/_abstract.scss
_sass/components/_links.scss
about.md

About page: add more info.

---

sponsors.html

Added sponsor types

---

.travis.yml

On hold until we have the new vnu version out.

Update vnu.jar to v18.8.29.

---

schedule.md

Updated schedule aka agenda

---

Gemfile
Gemfile.lock
package-lock.json
package.json

~~Waiting for a new jekyll-sitemap version which restores Ruby 2.4 support.~~

Update devDependencies and gems.

---

_includes/home/hero.html
_layouts/home.html
_sass/components/_abstract.scss

@XhmikosR I need help with the `#newsletter` anchor. Basically I the button to do a smooth scroll to the Newsletter section.

Updated home page hero content for the upcoming 2020 event

---

_includes/home/hero.html

@XhmikosR help me make this link white (and no hover color change)

Added sponsor link

---

_data/wgs.yml
working-groups/authentic-participation.md

@jdorfman pointed this out to me, so here is my first pass on filling
out the template on the Principles of Authentic Participation. I include
some helpful calls-to-action for folks who want to learn more or get
involved with what we have going so far.
Related to #238.

authentic-participation: Fill out template

---

working-groups/governance-readiness.md

This PR adds the contents for the Governance Readiness WG page.

Add Governance Readiness WG webpage

---

_config.yml
about.md
working-groups/index.md

@jdorfman edits

---

.github/workflows/ci.yml

Build and deploy the site with GitHub Actions.

---

_data/menu.yml
_includes/nav.html
manifesto.md

2-year-old issue now closed. Fixes #208

Add Sustainer Manifesto

---

working-groups/transparency-goals.md

Adds basic working group description.

Add Transparency WG

---

working-groups/ethics.md

Adding to the Ethics WG doc

---

working-groups/docs.md

Add office hours for projects to book a time for a chat

Add Office hours

---

working-groups/transparency-goals.md

Update existing Transparency working group with a final output and the current state.

Close Transparency Working Group

---

working-groups/personas.md

Adding the notes and a summary of the personas working session at Sustain 2020.

Notes/Summary of the Personas working session at Sustain 2020

---

_sass/components/_header-hero.scss

Fix contrast issues on main page

---

_includes/home/hero.html

| Before | After |
|---|---|
| <img width="740" alt="Screen Shot 2021-02-02 at 6 09 00 PM" src="https://user-images.githubusercontent.com/305339/106674882-0c36bd80-6582-11eb-9666-0b703c3d0d76.png"> | <img width="690" alt="Screen Shot 2021-02-02 at 6 09 07 PM" src="https://user-images.githubusercontent.com/305339/106674894-11940800-6582-11eb-9e79-cb890ec5f97c.png">
🎉 🎉 🎉 🎉 🎉 🎉

Fixed card formatting on homepage

---

Gemfile
Gemfile.lock
_data/menu.yml
_includes/footer.html
_includes/header.html
_includes/home/hero.html
_includes/home/newsletter.html
_includes/media/photos.html
_includes/media/podcasts-tab.html
_includes/nav.html
_layouts/blog.html
_layouts/post.html
_posts/2021-05-24-design-is-your-friend.md
_sass/_variables.scss
_sass/pages/_post.scss
assets/css/main.scss
blog.md

Hey @coderberry I think this is ready to roll sans illustration. We will pick up the design as part of a separate site we build around the report and posts like these. Thanks for helping keeping Mr. Hyde under wraps. 
<a href="https://gitpod.io/#https://github.com/sustainers/website/pull/303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add first report post

---

about.md

Also adding my own email.
<a href="https://gitpod.io/#https://github.com/sustainers/website/pull/328"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Adding note on rough consensus

---

_posts/SustainOSS-Organizing-Committee.md

Signed-off-by: Justin Dorfman <justindorfman@gmail.com>
<a href="https://gitpod.io/#https://github.com/sustainers/website/pull/343"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Fix MD lint issues

---

README.md
_posts/2022-08-08-sustainoss-organizing-committee.md
_posts/SustainOSS-Organizing-Committee.md

Signed-off-by: Justin Dorfman <justindorfman@gmail.com>
<a href="https://gitpod.io/#https://github.com/sustainers/website/pull/344"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add meta data to blog post

---

working-groups/academic-projects.md

Fixed typo in WG title

---

about/index.md

Move Justin from organizer to alumni

---

working-groups/diversity-equity-inclusion.md

This PR addresses issue #356  @RichardLitt  Please leave a review on this PR .

This PR Creates diversity-equity-inclusion.md file for the DEI working group #1

---

_posts/2023-11-06-rebooting-the-diversity-equity-and-inclusion-working-group-in-sustain.md

Just a brief article announcing the reboot of the DEI WG.
@RichardLitt  please give this a review

A call to participate article for the DEI WG

---

about/index.md

A missing word and one period too much.

Fix copyedit
